feat: support erc2771Forwarder
bnb-chain/greenfield-contracts pull request #149
Opened 2024-05-21 13:47 UTC by cosinlink

### Description
add erc2771Forwarder support  for GroupHub, BucketHub, ObjectHub, PermissionHub, TokenHub, MultiMessage and GreenfieldExecutor

### Changes

Notable changes:
* add erc2771Forwarder support  for GroupHub, BucketHub, ObjectHub, PermissionHub, TokenHub, MultiMessage and GreenfieldExecutor
* add IERC2771Forwarder interface

2024-05-24 08:24 UTC, Pythonberg1997 approved these changes

2024-05-24 08:53 UTC, unclezoro approved these changes

2024-05-28 02:22 UTC, unclezoro approved these changes

2024-05-28 02:22 UTC, unclezoro requested changes
need more review

2024-05-28 02:50 UTC, Pythonberg1997 approved these changes

2024-05-28 03:57 UTC, unclezoro approved these changes

2024-05-28 03:57 UTC, merged