feat(script): add verify scan scripts
bnb-chain/greenfield-contracts pull request #37
Opened 2023-05-25 02:14 UTC by cosinlink

### Description

add verify scan scripts

### Changes

Notable changes:
* add verify scan scripts
* ...

2023-05-25 08:17 UTC, SolidityGo commented on README.md
> +npm run deploy:testnet
fixed

2023-05-25 08:18 UTC, cosinlink commented on README.md
> +npm run deploy:testnet
fixed

2023-05-26 03:05 UTC, guagualvcha commented on foundry-scripts/TokenHub.s.sol
> +import "../contracts/Deployer.sol";
I don't think this is a good dependency cycle.

2023-05-26 03:19 UTC, guagualvcha requested changes
we need a refined command system, not only transfer out command.

2023-05-26 03:20 UTC, guagualvcha commented
Need to improve the readme

2023-05-26 07:37 UTC, guagualvcha approved these changes

2023-05-26 07:37 UTC, merged